-- Seed Turn 'n Slice product catalogue into ProcurePulse stock (pp_stock_items)
-- from the April 2026 price list. 800 products. Idempotent: skips any
-- product name that already exists for the org.
--
-- HOW TO APPLY: paste into the Supabase dashboard SQL editor and run once.
-- Change the org name on the WHERE line if you want a different workspace.

INSERT INTO pp_stock_items (org_id, name, unit, on_hand, low_threshold, avg_unit_price, currency)
SELECT o.id, v.name, v.unit, 0, 0, v.price, 'ZAR'
FROM (SELECT id FROM organisations WHERE name = 'Turn ''n Slice' LIMIT 1) o
CROSS JOIN (VALUES
  ('Chicken Livers (kg)','kg',100.0),
  ('Sweet Potato-Salad (Lt)','lt',29.5),
  ('Lunch Bar-Mini (23g)','23g',7.5),
  ('Mc-Cains','units',49.95),
  ('Mushroom-Sliced (kg)','kg',89.95),
  ('Oranges-Imported','units',44.9),
  ('Potato Chips Froz Mc-Cains','units',49.95),
  ('Simba-Assorted(36g) Pkts','units',9.95),
  ('Amadumbe (kg)','kg',22.5),
  ('Amaranth Feather (pkt)','pkt',31.5),
  ('Apple-Blossom (pkt)','pkt',44.9),
  ('Apples-Golden (box)','box',499.0),
  ('Apples-Golden (ea)','ea',2.75),
  ('Apples-Golden (kg)','kg',23.8),
  ('Apples-Green (box)','box',285.0),
  ('Apples-Green (ea)','ea',2.5),
  ('Apples-Green (kg)','kg',23.8),
  ('Apples-Red (box)','box',326.5),
  ('Apples-Red (ea)','ea',4.5),
  ('Apples-Red Starking (kg)','kg',23.8),
  ('Apples-Toffee  (ea)','ea',12.5),
  ('Apples-Top Red (kg)','kg',23.8),
  ('Apples - Dried (kg)','kg',89.0),
  ('Apples Baby (Kg)','kg',12.0),
  ('Apricots-Dried (kg)','kg',65.56),
  ('Apricots (box)','box',225.0),
  ('Apricots (kg)','kg',45.0),
  ('Apricots (pkt)','pkt',22.4),
  ('Artichokes (box)','box',135.0),
  ('Artichokes (kg)','kg',49.0),
  ('Artichokes (pkt)','pkt',32.75),
  ('Asian Slaw Mix (kg)','kg',39.5),
  ('Asparagus-Green (kg)','kg',369.0),
  ('Asparagus-Green (pkt)','pkt',79.9),
  ('Asparagus-White (kg)','kg',189.5),
  ('Asparagus-White (pkt)','pkt',62.5),
  ('Atchar (kg)','kg',66.0),
  ('Avocado-Fuerte (box)','box',285.0),
  ('Avocado-Fuerte (kg)','kg',72.5),
  ('Avocado-Plup (kg)','kg',75.0),
  ('Avocado-Sliced Frozen (kg)','kg',58.0),
  ('Avocado (box)','box',155.0),
  ('Avocado (ea)','ea',10.9),
  ('Avocado (kg)','kg',44.7),
  ('Avocado (pkt)','pkt',22.5),
  ('Baby Carrots-Coloured (kg)','kg',139.5),
  ('Baby Carrots-Coloured (pkt)','pkt',26.9),
  ('Baby Carrots-Peeled (kg)','kg',34.5),
  ('Baby Carrots (kg)','kg',89.7),
  ('Baby Carrots (pkt)','pkt',22.5),
  ('Baby Carrots w/green (kg)','kg',126.5),
  ('Baby Corn (kg)','kg',189.4),
  ('Baby Corn (pkt)','pkt',28.9),
  ('Baby Gems (kg)','kg',69.7),
  ('Baby Gems (pkt)','pkt',22.8),
  ('Baby Marrow-Battons (kg)','kg',59.9),
  ('Baby Marrow-Diced (kg)','kg',39.9),
  ('Baby Marrow-Flowers (kg)','kg',97.75),
  ('Baby Marrow-Flowers (pun)','pun',12.5),
  ('Baby Marrow-Grated (kg)','kg',36.9),
  ('Baby Marrow-Julienne (kg)','kg',49.9),
  ('Baby Marrow-Noodles (kg)','kg',69.0),
  ('Baby Marrow-Sliced (kg)','kg',39.9),
  ('Baby Marrow-Turned (kg)','kg',39.5),
  ('Baby Marrow-Yellow (kg)','kg',25.0),
  ('Baby Marrow-Yellow (pun)','pun',12.0),
  ('Baby Marrow (box)','box',74.5),
  ('Baby Marrow (kg)','kg',29.8),
  ('Baby Marrow (pkt)','pkt',22.5),
  ('Baby Marrow Ribbons (kg)','kg',59.5),
  ('Bacon (kg)','kg',119.9),
  ('Banana-Dried (kg)','kg',157.5),
  ('Banana-Frozen (kg)','kg',18.95),
  ('Banana-Leaves (box)','box',269.0),
  ('Banana - Peeled (kg)','kg',18.95),
  ('Banana (box)','box',459.0),
  ('Banana (ea)','ea',3.5),
  ('Banana (kg)','kg',26.9),
  ('Basil-Imported (Kg)','kg',175.0),
  ('Basil-Pesto (kg)','kg',259.0),
  ('Basil-Purple (kg)','kg',125.0),
  ('Basil-Purple (pkt)','pkt',25.0),
  ('Basil (kg)','kg',135.0),
  ('Basil (pkt)','pkt',32.9),
  ('Basil (pkt) 100gr','units',18.5),
  ('Bay Leaves (pkt)','pkt',35.0),
  ('Bean-Bundles (ea)','ea',3.0),
  ('Bean-Salad (lt)','lt',54.5),
  ('Bean & Potato Mix (kg)','kg',29.95),
  ('Beans-Barlotti  /kg','units',32.9),
  ('Beans-Green (pkt)','pkt',9.9),
  ('Beans-Kenya (kg)','kg',39.9),
  ('Beans (tin)','tin',119.0),
  ('Beans Broad (box)','box',89.0),
  ('Beans Broad (Kg)','kg',26.0),
  ('Beans Broad Frozen (pkt)','pkt',34.0),
  ('Beans Green-Cleaned (kg)','kg',46.9),
  ('Beans Green-Cut (kg)','kg',46.9),
  ('Beans Green-Whole (box)','box',74.5),
  ('Beans Green-Whole (kg)','kg',38.7),
  ('Beetroot-Baby (kg)','kg',21.4),
  ('Beetroot-Candy Stripe (kg)','kg',99.0),
  ('Beetroot-Cooked (kg)','kg',39.5),
  ('Beetroot-Diced (kg)','kg',39.5),
  ('Beetroot-Golden (kg)','kg',99.9),
  ('Beetroot-Grated (kg)','kg',17.5),
  ('Beetroot-Julienne (kg)','kg',39.5),
  ('Beetroot-noodles (Kg)','kg',39.95),
  ('Beetroot-Peeled (kg)','kg',39.9),
  ('Beetroot-Salad (lt)','lt',45.0),
  ('Beetroot-Sliced (kg)','kg',39.5),
  ('Beetroot-Wedges (kg)','kg',19.5),
  ('Beetroot (bag)','bag',65.0),
  ('Beetroot (kg)','kg',21.4),
  ('Beetroot Candy Stripe (pkt)','pkt',32.7),
  ('Berry Kebabs (ea)','ea',8.95),
  ('Blackberries-Frozen (kg)','kg',99.0),
  ('Blackberries (kg)','kg',289.0),
  ('Blackberries (pun)','pun',29.4),
  ('Blueberries-Frozen (kg)','kg',109.0),
  ('Blueberries (kg)','kg',389.0),
  ('Blueberries (pun)','pun',42.4),
  ('Bokchoi-Baby (kg)','kg',89.9),
  ('Bokchoi (kg)','kg',66.9),
  ('Bokchoi (pkt)','pkt',21.5),
  ('Braai Spice (kg)','kg',179.0),
  ('Bread-Brown (ea)','ea',19.95),
  ('Bread-Low GI  (ea)','ea',15.0),
  ('Bread-Rye (ea)','ea',29.95),
  ('Bread-White (ea)','ea',19.95),
  ('Bread-Wholewheat (ea)','ea',12.0),
  ('Brinjals-Baby (kg)','kg',39.9),
  ('Brinjals-Baby (pkt)','pkt',15.0),
  ('Brinjals-Diced (kg)','kg',59.5),
  ('Brinjals-Sliced (kg)','kg',55.0),
  ('Brinjals (box)','box',109.9),
  ('Brinjals (ea)','ea',5.5),
  ('Brinjals (kg)','kg',23.8),
  ('Broccoli-Florets (kg)','kg',109.0),
  ('Broccoli-Long Stem (kg)','kg',128.0),
  ('Broccoli-Long Stem (pkt)','pkt',23.95),
  ('Broccoli-Whole (kg)','kg',86.7),
  ('Broccoli-Whole (pkt)','pkt',27.9),
  ('Broccoli & Cauliflower-Mix (kg)','kg',88.0),
  ('Brusselsprouts (kg)','kg',98.0),
  ('Brusselsprouts (pkt)','pkt',29.9),
  ('Bucket (5lt)','5lt',14.5),
  ('Bundles-Mixed (ea)','ea',6.75),
  ('Butternut-Baby (kg)','kg',89.0),
  ('Butternut-Baby (pun)','pun',21.4),
  ('Butternut-Cubed (kg)','kg',16.9),
  ('Butternut-Disks (kg)','kg',28.5),
  ('Butternut-Grated (kg)','kg',24.5),
  ('Butternut-Halves (ea)','ea',4.5),
  ('Butternut-Halves (Kg)','kg',14.9),
  ('Butternut-Julienne (kg)','kg',22.5),
  ('Butternut-Noodles (kg)','kg',49.5),
  ('Butternut-Peeled (kg)','kg',17.9),
  ('Butternut-Sliced-kg','units',19.5),
  ('Butternut-Turned (kg)','kg',35.0),
  ('Butternut-Whole (bag)','bag',83.5),
  ('Butternut-Whole (each)','each',16.9),
  ('Butternut-Whole (kg)','kg',7.9),
  ('Butternut-Whole 7kg (bag)','bag',85.5),
  ('Butternut-Whole Small (kg)','kg',8.9),
  ('Butternut - Battons (kg)','kg',18.5),
  ('Cabbage-Baby (kg)','kg',39.8),
  ('Cabbage-Baby (pkt)','pkt',13.75),
  ('Cabbage-Chinese (ea)','ea',34.5),
  ('Cabbage-Chinese (kg)','kg',28.9),
  ('Cabbage-Mixed Sliced (kg)','kg',39.75),
  ('Cabbage-Red (ea)','ea',25.9),
  ('Cabbage-Red (kg)','kg',38.5),
  ('Cabbage-Savoy (kg)','kg',38.5),
  ('Cabbage-Savoy (pkt)','pkt',11.0),
  ('Cabbage-White (bag)','bag',169.0),
  ('Cabbage-White (box)','box',79.7),
  ('Cabbage-White (ea)','ea',22.5),
  ('Cabbage-White (kg)','kg',8.9),
  ('Cabbage & Spinach-Sliced (kg)','kg',26.5),
  ('Cabbage (W) quater-cut(Kg)','kg',12.9),
  ('Cabbage Red-Sliced (kg)','kg',39.9),
  ('Cabbage White-Sliced (kg)','kg',14.9),
  ('Cardamom Whole (kg)','kg',1200.0),
  ('Carrot-Bundles (ea)','ea',3.0),
  ('Carrot-Noodles (kg)','kg',35.0),
  ('Carrot & Bean Mix (Kg)','kg',22.75),
  ('Carrot & Leek Mix (kg)','kg',28.75),
  ('Carrot & Pine Salad (lt)','lt',32.5),
  ('Carrot & Potato Mix (kg)','kg',12.95),
  ('Carrot Ribbons (kg)','kg',49.5),
  ('Carrots-Battons (kg)','kg',27.9),
  ('Carrots-Coloured (kg)','kg',119.4),
  ('Carrots-Diced (kg)','kg',16.7),
  ('Carrots-Grated (kg)','kg',16.7),
  ('Carrots-Julienne (kg)','kg',16.7),
  ('Carrots-Peeled (kg)','kg',15.9),
  ('Carrots-Sliced (kg)','kg',22.5),
  ('Carrots-Turned (kg)','kg',39.0),
  ('Carrots-Whole (bag)','bag',85.5),
  ('Carrots-Whole (kg)','kg',11.7),
  ('Carrots Baby-Coloured (pkt)','pkt',22.0),
  ('Cassava (kg)','kg',55.0),
  ('Cauliflower-Florets (kg)','kg',98.0),
  ('Cauliflower-Rice (kg)','kg',45.0),
  ('Cauliflower-Whole (ea)','ea',29.7),
  ('Cauliflower-Whole (kg)','kg',84.8),
  ('Celeriac (box)','box',244.0),
  ('Celeriac (kg)','kg',49.0),
  ('Celery-Battons (kg)','kg',39.5),
  ('Celery-Diced (kg)','kg',67.5),
  ('Celery (bunch)','bunch',27.7),
  ('Celery (kg)','kg',48.7),
  ('Chakalaka Salad (lt)','lt',69.9),
  ('Chard (kg)','kg',67.5),
  ('Charka Braai Briquettes /bag','units',109.0),
  ('Cheese (kg)','kg',216.5),
  ('Cherries-Frozen (kg)','kg',89.0),
  ('Cherries (kg)','kg',219.0),
  ('Cherries (pkt)','pkt',49.9),
  ('Chervil (kg)','kg',75.0),
  ('Chervil (pkt)','pkt',13.5),
  ('Chicory (kg)','kg',99.99),
  ('Chicory (pkt)','pkt',45.0),
  ('Chillie-Flakes (kg)','kg',190.0),
  ('Chillies-Green (kg)','kg',56.9),
  ('Chillies-Green (pkt)','pkt',8.5),
  ('Chillies-Habanero (kg)','kg',79.0),
  ('Chillies-Jallapeno (kg)','kg',48.4),
  ('Chillies-Mixed (kg)','kg',56.9),
  ('Chillies-Red (bag)','bag',109.0),
  ('Chillies-Red (kg)','kg',56.9),
  ('Chillies-Red (pkt)','pkt',16.5),
  ('Chillies-Sliced (kg)','kg',89.0),
  ('Chip-White (kg)','kg',26.5),
  ('Chives (kg)','kg',199.0),
  ('Chives (pkt)','pkt',18.5),
  ('Clementines (kg)','kg',23.5),
  ('Coconut-Milk (tin)','tin',39.9),
  ('Coconuts (bag)','bag',450.0),
  ('Coconuts (ea)','ea',11.0),
  ('Coconuts (kg)','kg',17.4),
  ('Coleslaw Mix (kg)','kg',12.95),
  ('Coleslaw Salad (lt)','lt',33.9),
  ('Copper Penny Salad (l)','l',39.95),
  ('Coriander Seeds (kg)','kg',130.0),
  ('Corn-Frozen (kg)','kg',47.7),
  ('Cranberries-Frozen (kg)','kg',115.0),
  ('Cream-Fresh /l','units',139.0),
  ('Cucamelon (kg)','kg',69.0),
  ('Cucumber-Battons (kg)','kg',48.5),
  ('Cucumber & Pine Salad (lt)','lt',29.5),
  ('Cucumbers (ea)','ea',14.7),
  ('Cucumbers (kg)','kg',46.8),
  ('Cumin Ground (kg)','kg',265.0),
  ('Cumquats (kg)','kg',39.9),
  ('Curry Leaves (kg)','kg',169.0),
  ('Curry Leaves (pkt)','pkt',39.9),
  ('Curry Pasta Salad (lt)','lt',49.9),
  ('Curry Paste (ea)','ea',59.0),
  ('Danya (bunch)','bunch',24.4),
  ('Danya (kg)','kg',99.0),
  ('Dates (kg)','kg',139.0),
  ('Dates (pkt)','pkt',29.0),
  ('Delivery Charge','units',200.0),
  ('Dill (kg)','kg',129.0),
  ('Dill (pkt)','pkt',28.5),
  ('Dill (pkt) 100gr','units',14.5),
  ('Dragonfruit (kg)','kg',95.0),
  ('Dragonfruit (pkt)','pkt',39.0),
  ('Dried-Mix Fruit (kg)','kg',165.0),
  ('Dried Prunes (kg)','kg',185.0),
  ('Edamame Beans (kg)','kg',129.95),
  ('Edible Flowers  (kg)','kg',359.0),
  ('Edible Flowers (pkt)','pkt',23.9),
  ('Eggs (15 doz bx) XL','units',429.5),
  ('Eggs (MED) 15 doz box','units',356.5),
  ('Eggs Large 15/doz box','units',389.5),
  ('Endives (box)','box',135.0),
  ('Endives (kg)','kg',12.0),
  ('Endives (pkt)','pkt',25.0),
  ('Fennel-Baby (kg)','kg',98.0),
  ('Fennel-Baby (pkt)','pkt',19.75),
  ('Fennel-Bulb (kg)','kg',48.9),
  ('Fennel-Flowers (pkt)','pkt',31.5),
  ('Fennel Seeds (kg)','kg',189.0),
  ('Ferrero Rocher (box)','box',200.0),
  ('Figs-Dried (kg)','kg',169.0),
  ('Figs (box)','box',117.0),
  ('Figs (kg)','kg',109.0),
  ('Figs (pkt)','pkt',39.9),
  ('Flowers-bunch','units',129.95),
  ('Flowers-Hibiscus (pkt)','pkt',26.9),
  ('Flowers-Nasturtiums (pkt)','pkt',26.9),
  ('Flowers-Pansies (pkt)','pkt',22.5),
  ('Flowers-Violas (pkt)','pkt',26.9),
  ('Foil (ea)','ea',99.95),
  ('French Salad (lt)','lt',49.9),
  ('Fruit Kebabs (ea)','ea',7.75),
  ('Fruit Salad (lt)','lt',65.0),
  ('Garlic-Crushed (kg)','kg',66.8),
  ('Garlic-Peeled (kg)','kg',189.0),
  ('Garlic-Powder (kg)','kg',190.0),
  ('Garlic-Whole (kg)','kg',99.0),
  ('Gem Squash-Halves (ea)','ea',2.95),
  ('Gem Squash-Halves (kg)','kg',28.9),
  ('Gem Squash (bag)','bag',84.5),
  ('Gem Squash (ea)','ea',2.5),
  ('Gem Squash (kg)','kg',13.9),
  ('Gherkins (Kg)','kg',11.0),
  ('Gherkins (Pkt)','pkt',16.5),
  ('Ginger-Crushed (kg)','kg',97.9),
  ('Ginger-Dried-(kg)','kg',259.95),
  ('Ginger-Peeled (kg)','kg',99.0),
  ('Ginger-Whole (kg)','kg',99.0),
  ('Gooseberries-Frozen (kg)','kg',99.0),
  ('Gooseberries (kg)','kg',299.0),
  ('Gooseberries (pun)','pun',35.5),
  ('Granadilla (kg)','kg',99.8),
  ('Granadilla (pkt)','pkt',39.5),
  ('Grapefruit-Peeled (kg)','kg',29.5),
  ('Grapefruit-Segments (lt)','lt',98.0),
  ('Grapefruit-Sliced (lt)','lt',39.75),
  ('Grapefruit (bag)','bag',56.75),
  ('Grapefruit (box) large box','units',147.5),
  ('Grapefruit (ea)','ea',3.0),
  ('Grapefruit (kg)','kg',15.7),
  ('Grapes-Black (box)','box',269.7),
  ('Grapes-Black (kg)','kg',59.9),
  ('Grapes-Black (pun)','pun',26.9),
  ('Grapes-Mixed (kg)','kg',34.95),
  ('Grapes-Mixed (pun)','pun',28.0),
  ('Grapes-Red (box)','box',225.0),
  ('Grapes-Red (Kg)','kg',59.9),
  ('Grapes-White (box)','box',299.7),
  ('Grapes-White (kg)','kg',59.9),
  ('Grapes-White (pun)','pun',29.9),
  ('Greek Salad (L)','l',36.75),
  ('Guava-Dried (kg)','kg',267.5),
  ('Guava (box)','box',82.5),
  ('Guava (kg)','kg',39.4),
  ('Hashbrowns Frozen (Kg)','kg',26.99),
  ('Horseradish (kg)','kg',15.0),
  ('Hubbard Squash-Cut (kg)','kg',13.95),
  ('Hubbard Squash (Bag)','bag',95.0),
  ('Hubbard Squash (ea)','ea',22.0),
  ('Hubbard Squash (kg)','kg',7.8),
  ('Internal Stock Exchange','units',0.01),
  ('Jerusalem Artichokes (Kg)','kg',67.5),
  ('Juice-Assorted (lt)','lt',55.0),
  ('Kale (box)','box',99.0),
  ('Kale (bunch)','bunch',13.5),
  ('Kale (kg)','kg',27.5),
  ('Kashmiri Chilli Powder (kg)','kg',330.0),
  ('Kebabs-Vegetable (ea)','ea',8.9),
  ('Kiwifruit-Golden (kg)','kg',46.5),
  ('Kiwifruit (box)','box',229.0),
  ('Kiwifruit (kg)','kg',95.7),
  ('Kiwifruit (pun)','pun',38.9),
  ('Kohlrabi  (box)','box',125.0),
  ('Kohlrabi (kg)','kg',25.0),
  ('Lavender  (kg)','kg',88.0),
  ('Leeks-Baby (kg)','kg',99.0),
  ('Leeks-Baby (pkt)','pkt',24.7),
  ('Leeks-sliced (kg)','kg',69.95),
  ('Leeks  (bunch)','bunch',59.9),
  ('Leeks  (kg)','kg',49.9),
  ('Lemon Grass (kg)','kg',118.0),
  ('Lemon Grass (pkt)','pkt',24.75),
  ('Lemon Grass (pkt) 100gr','units',14.5),
  ('Lemon Verbena (pkt)','pkt',22.5),
  ('Lemon Verbena Flowers (kg)','kg',295.0),
  ('Lemons (bag)','bag',77.7),
  ('Lemons (box)','box',74.4),
  ('Lemons (ea)','ea',1.9),
  ('Lemons (kg)','kg',12.9),
  ('Lettuce-Baby Gem (Kg)','kg',69.0),
  ('Lettuce-Baby Gem (pkt)','pkt',12.0),
  ('Lettuce-Baby Leaf (kg)','kg',159.5),
  ('Lettuce-Baby leaf (pkt)','pkt',19.5),
  ('Lettuce-Butter (kg)','kg',59.0),
  ('Lettuce-Butter (pkt)','pkt',18.95),
  ('Lettuce-Butter /box','units',169.0),
  ('Lettuce-Cos (box)','box',165.0),
  ('Lettuce-Cos (kg)','kg',46.9),
  ('Lettuce-Cos (pkt)','pkt',20.9),
  ('Lettuce-Frisee (kg)','kg',45.0),
  ('Lettuce-Iceberg (box)','box',109.0),
  ('Lettuce-Iceberg (ea)','ea',18.9),
  ('Lettuce-Iceberg (kg)','kg',37.7),
  ('Lettuce-Mix (box)','box',122.5),
  ('Lettuce-Mix (kg)','kg',54.9),
  ('Lettuce-Mix (pkt)','pkt',19.5),
  ('Lime-Leaves (pkt)','pkt',28.0),
  ('Limes (kg)','kg',39.8),
  ('Litchies (kg)','kg',99.0),
  ('Litchies (pun)','pun',34.9),
  ('Mango-Dried (kg)','kg',399.0),
  ('Mango-Frozen (kg)','kg',125.0),
  ('Mango (box)','box',149.9),
  ('Mango (ea)','ea',26.75),
  ('Mango (kg)','kg',54.7),
  ('Marjoram (kg)','kg',88.9),
  ('Marjoram (pkt)','pkt',26.75),
  ('Mayonaise (20Lt)','20lt',895.0),
  ('Micro Greens (kg)','kg',145.0),
  ('Micro Greens (pkt)','pkt',68.9),
  ('Micro Greens 350 gr (tub)','tub',68.9),
  ('Micro Herbs (tray)','tray',36.5),
  ('Micro Leaf Shoots (pkt)','pkt',49.9),
  ('Micro Shoots-Pre Mix (pkt)','pkt',39.9),
  ('Micro Shoots (kg)','kg',355.5),
  ('Milk-full Cream /2Lt','units',36.0),
  ('Milk-Low fat /2Lt','units',36.0),
  ('Milk /L','units',21.8),
  ('Mint (kg)','kg',116.0),
  ('Mint (pkt)','pkt',27.75),
  ('Mint (pkt) 100gr','units',14.5),
  ('Mirepoix Mix (kg)','kg',46.9),
  ('Mix-Veg-Brunoise /kg','units',55.75),
  ('Mix Berries-Frozen (kg)','kg',109.0),
  ('Mix Veg-Country (kg)','kg',55.9),
  ('Mix Veg-Frozen (kg)','kg',49.9),
  ('Mix Veg-Green  (kg)','kg',42.5),
  ('Mix Veg-Poitjiekos (kg)','kg',39.75),
  ('Mix Veg-Roast (Kg)','kg',55.9),
  ('Mix Veg-Root Veg (kg)','kg',39.75),
  ('Mix Veg - Baby (kg)','kg',56.5),
  ('Mizuna (kg)','kg',125.0),
  ('Morogo (box)','box',49.5),
  ('Morogo (kg)','kg',29.5),
  ('Mozzie Candles (ea)','ea',59.0),
  ('Mushroom-Brown (box)','box',222.5),
  ('Mushroom-Brown (ea)','ea',3.5),
  ('Mushroom-Brown (kg)','kg',136.5),
  ('Mushroom-Brown (pkt)','pkt',29.9),
  ('Mushroom-Eryngi (kg)','kg',235.0),
  ('Mushroom-Eryngi (pkt)','pkt',57.5),
  ('Mushroom-King Oyster (250gr pkt','units',57.5),
  ('Mushroom-Oyster (kg)','kg',109.0),
  ('Mushroom-Oyster (pun)','pun',33.9),
  ('Mushroom-Porcini (kg)','kg',419.0),
  ('Mushroom-Porcini Frozen (kg)','kg',245.0),
  ('Mushroom-Portabellini (kg)','kg',118.0),
  ('Mushroom-Portabellini (pun)','pun',28.75),
  ('Mushroom-Shimeji (kg)','kg',199.0),
  ('Mushroom-Shimeji (pun)','pun',33.5),
  ('Mushroom-Shimeji Brown (kg)','kg',199.0),
  ('Mushroom-Shimeji White (kg)','kg',199.0),
  ('Mushroom-Shitake (kg)','kg',248.0),
  ('Mushroom-White (box)','box',389.9),
  ('Mushroom-White (kg)','kg',78.8),
  ('Mushroom-White (pun)','pun',29.9),
  ('Mushroom-White Sliced (kg)','kg',99.0),
  ('Mushroom-Wild Mix (kg)','kg',229.0),
  ('Mushroom Salad (lt)','lt',45.0),
  ('Mushroom Shitake Pkt (100g)','100g',26.9),
  ('Mushroom Wild Mix Pkt (250g)','250g',59.0),
  ('Mushrooms-Shitake (250gr pkt)','250gr pkt',57.5),
  ('Mustard-Frilly (pkt)','pkt',31.5),
  ('Mutton Curry Spice (kg)','kg',245.0),
  ('Naartjies-Small Box (box)','box',49.9),
  ('Naartjies (box)','box',145.0),
  ('Naartjies (ea)','ea',3.5),
  ('Naartjies (kg)','kg',24.4),
  ('Nectacots (box)','box',148.5),
  ('Nectacots (kg)','kg',9.75),
  ('Nectacots (pun)','pun',22.5),
  ('Nectarines (box)','box',146.5),
  ('Nectarines (ea)','ea',5.75),
  ('Nectarines (kg)','kg',49.8),
  ('Nectarines (pkt)','pkt',37.9),
  ('Nusturtium leaves (pkt)','pkt',36.9),
  ('Okra (box)','box',69.75),
  ('Okra (kg)','kg',58.0),
  ('Onion-Brunoised (kg)','kg',25.0),
  ('Onion-Diced (kg)','kg',26.9),
  ('Onion-Peeled (kg)','kg',15.9),
  ('Onion-Red (bag)','bag',247.4),
  ('Onion-Red (kg)','kg',20.9),
  ('Onion-Red Peeled (kg)','kg',24.4),
  ('Onion-Red Sliced (kg)','kg',49.5),
  ('Onion-Rings (kg)','kg',24.9),
  ('Onion-Sliced (kg)','kg',24.9),
  ('Onion-Whole (bag)','bag',119.5),
  ('Onion-Whole (kg)','kg',9.8),
  ('Onion Baby-Peeled  (kg)','kg',18.5),
  ('Onion Baby-Whole (kg)','kg',8.9),
  ('Onion Red-Diced (kg)','kg',22.0),
  ('Onion Red-Sliced (kg)','kg',39.9),
  ('Orange - Peeled (Ltr)','ltr',49.95),
  ('Orange Segments (Lt)','lt',69.0),
  ('Oranges-Imported (Kg)','kg',46.9),
  ('Oranges-Sliced (lt)','lt',49.5),
  ('Oranges (bag)','bag',62.4),
  ('Oranges (box)','box',189.0),
  ('Oranges (ea)','ea',2.5),
  ('Oranges (kg)','kg',13.9),
  ('Oregano (kg)','kg',88.9),
  ('Oregano (pkt)','pkt',26.5),
  ('Oreganum (pkt) 100gr','units',14.5),
  ('Orient Basmati Rice (bag)','bag',190.0),
  ('Oyster-leaves (pkt)','pkt',44.9),
  ('Parsley-Italian (kg)','kg',118.0),
  ('Parsley-Italian (pkt)','pkt',26.9),
  ('Parsley-Italian (pkt) 100gr','units',14.5),
  ('Parsley (box)','box',115.0),
  ('Parsley (bunch)','bunch',19.9),
  ('Parsley (kg)','kg',89.0),
  ('Parsnips (kg)','kg',99.0),
  ('Parsnips (pkt)','pkt',45.9),
  ('Pasta Salad (lt)','lt',43.9),
  ('Patty Pans-Diced (kg)','kg',85.0),
  ('Patty Pans-Green (kg)','kg',79.4),
  ('Patty Pans-Green (pun)','pun',26.9),
  ('Patty Pans-Mixed (kg)','kg',65.75),
  ('Patty Pans-Mixed (pun)','pun',16.75),
  ('Patty Pans-Yellow (kg)','kg',79.4),
  ('Patty Pans-Yellow (pun)','pun',27.5),
  ('Paw Paw-Diced (lt)','lt',49.5),
  ('PawPaw (box)','box',197.5),
  ('PawPaw (ea)','ea',23.9),
  ('PawPaw (kg)','kg',39.5),
  ('PawPaw (pkt)','pkt',56.4),
  ('Peaches - Dried (kg)','kg',89.0),
  ('Peaches (box)','box',98.5),
  ('Peaches (ea)','ea',5.3),
  ('Peaches (kg)','kg',42.7),
  ('Peaches (pkt)','pkt',23.9),
  ('Pears-Red (kg)','kg',16.95),
  ('Pears (box)','box',239.0),
  ('Pears (ea)','ea',3.99),
  ('Pears (kg)','kg',20.9),
  ('Peas-Frozen (kg)','kg',56.5),
  ('Pecan Nuts (kg)','kg',106.5),
  ('Pepper Green-Julienne (kg)','kg',49.5),
  ('Pepper Steak Spice (kg)','kg',245.0),
  ('Peppers-Baby (kg)','kg',16.5),
  ('Peppers-Green (box)','box',124.7),
  ('Peppers-Green (ea)','ea',8.75),
  ('Peppers-Green (kg)','kg',39.7),
  ('Peppers-Jallapeno (kg)','kg',37.5),
  ('Peppers-Mixed (box)','box',169.0),
  ('Peppers-Mixed (ea)','ea',10.9),
  ('Peppers-Mixed (kg)','kg',57.5),
  ('Peppers-Red (box)','box',269.0),
  ('Peppers-Red (ea)','ea',14.9),
  ('Peppers-Red (kg)','kg',68.4),
  ('Peppers-Yellow (box)','box',179.0),
  ('Peppers-Yellow (ea)','ea',11.5),
  ('Peppers-Yellow (kg)','kg',66.4),
  ('Peppers-Yellow Julienne (kg)','kg',59.0),
  ('Peppers Green-Diced (kg)','kg',49.0),
  ('Peppers Green-Julienne (kg)','kg',39.0),
  ('Peppers Mix-Diced (kg)','kg',89.9),
  ('Peppers Mix-Julienne (kg)','kg',89.9),
  ('Peppers Mixed-Bruinoised (kg)','kg',59.75),
  ('Peppers Red-Diced (kg)','kg',49.0),
  ('Peppers Red-Julienne (kg)','kg',59.0),
  ('Peri Peri Chicken Spice (kg)','kg',180.0),
  ('Persimmon (box)','box',69.0),
  ('Persimmon (pkt)','pkt',27.9),
  ('Persimmons (kg)','kg',49.0),
  ('Pineapples-Diced (kg)','kg',39.9),
  ('Pineapples-Diced (litre)','litre',69.5),
  ('Pineapples-Frozen (kg)','kg',49.5),
  ('Pineapples-Parisienne (lt)','lt',39.5),
  ('Pineapples-Sliced (lt)','lt',49.0),
  ('Pineapples (box)','box',138.75),
  ('Pineapples (ea)','ea',15.9),
  ('Pineapples (kg)','kg',19.8),
  ('Plantain  (kg)','kg',39.0),
  ('Plums (box)','box',69.0),
  ('Plums (ea)','ea',2.5),
  ('Plums (kg)','kg',32.7),
  ('Plums (pkt)','pkt',25.8),
  ('Pomegranate-Rubies (tub)','tub',49.9),
  ('Pomegranate-seed (pkt)','pkt',59.95),
  ('Pomegranate (ea)','ea',12.0),
  ('Pomegranates - Imported (Kg)','kg',179.0),
  ('Pomegranates (box)','box',138.5),
  ('Pomegrante-seed (kg)','kg',319.0),
  ('Pomegrante (kg)','kg',69.0),
  ('Pomelo (kg)','kg',18.5),
  ('Potato-Chips Fresh (kg)','kg',16.9),
  ('Potato-Chips Fresh w/skin (kg)','kg',22.5),
  ('Potato-Chips Frozen 10mm (kg)','kg',36.5),
  ('Potato-Chips Frozen 7MM (kg)','kg',40.9),
  ('Potato-Diced (kg)','kg',16.9),
  ('Potato-Foiled (ea)','ea',2.5),
  ('Potato-Fondant (KG)','kg',33.5),
  ('Potato-Grated (kg)','kg',11.95),
  ('Potato-Large (bag)','bag',84.4),
  ('Potato-Large (kg)','kg',11.9),
  ('Potato-Med (bag)','bag',84.4),
  ('Potato-Medium (kg)','kg',11.9),
  ('Potato-New (bag)','bag',75.0),
  ('Potato-New (kg)','kg',9.8),
  ('Potato-New Peeled (kg)','kg',18.9),
  ('Potato-New Salad (lt)','lt',29.5),
  ('Potato-Noodles (kg)','kg',49.5),
  ('Potato-Parisienne (kg)','kg',29.9),
  ('Potato-Peeled (kg)','kg',16.7),
  ('Potato-Pruple (kg)','kg',9.5),
  ('Potato-Quarter Cut (kg)','kg',16.9),
  ('Potato-Sliced (kg)','kg',22.9),
  ('Potato-Small Diced (kg)','kg',11.95),
  ('Potato-Sumo (kg)','kg',28.95),
  ('Potato-Turned (kg)','kg',34.9),
  ('Potato-Wedges (kg)','kg',19.9),
  ('Potato-Wedges Frozen (kg)','kg',16.0),
  ('Potato Chips-Frozen 12mm (kg)','kg',39.9),
  ('Potato Chips-Rustic Frozen (kg)','kg',37.9),
  ('Potato Salad (lt)','lt',46.5),
  ('Prawn Spice (kg)','kg',190.0),
  ('Prickly Pears (box)','box',81.5),
  ('Prickly Pears (kg)','kg',69.7),
  ('Prickly Pears (pkt)','pkt',33.5),
  ('Pumkin-Wedges (kg)','kg',16.95),
  ('Pumpkin-Battons (kg)','kg',16.95),
  ('Pumpkin-Cubed (kg)','kg',16.5),
  ('Pumpkin-Halloween (Ea)','ea',85.0),
  ('Pumpkin-Julienne (kg)','kg',9.5),
  ('Pumpkin-Peeled (kg)','kg',16.5),
  ('Pumpkin-Sliced (kg)','kg',13.5),
  ('Pumpkin-Whole (kg)','kg',7.2),
  ('Pumpkin - Grated (kg)','kg',8.75),
  ('Pumpkin (bag)','bag',165.0),
  ('Pumpkin (ea)','ea',21.5),
  ('Quince (box)','box',59.0),
  ('Quince (kg)','kg',24.0),
  ('Radicchio (kg)','kg',69.0),
  ('Radicchio (pkt)','pkt',27.9),
  ('Radish-Black (kg)','kg',139.0),
  ('Radish-Coloured (kg)','kg',89.0),
  ('Radish-Micro /kg','units',59.5),
  ('Radish-White /kg','units',26.9),
  ('Radish (bunch)','bunch',22.8),
  ('Radish (kg)','kg',89.0),
  ('Raspberries-Frozen (kg)','kg',139.0),
  ('Raspberries (kg)','kg',259.0),
  ('Raspberries (pun)','pun',27.5),
  ('Ratatoullie Mix (kg)','kg',46.75),
  ('Reversal of Credit Note','units',484.2),
  ('Rhubarb (kg)','kg',46.9),
  ('Rhubarb (pkt)','pkt',22.5),
  ('Rocket-Wild (kg)','kg',129.5),
  ('Rocket-Wild (Pkt)','pkt',29.75),
  ('Rocket-Wild (pkt) 100gr','units',14.5),
  ('Rocket (kg)','kg',129.5),
  ('Rocket (pkt)','pkt',29.75),
  ('Rocket (pkt) 100gr','units',14.5),
  ('Romanesco  (kg)','kg',55.0),
  ('Romanesco  (pkt)','pkt',14.0),
  ('Rose-Petals (pkt)','pkt',130.0),
  ('Rosemary (kg)','kg',108.0),
  ('Rosemary (pkt)','pkt',27.5),
  ('Rosemary (pkt) 100gr','units',14.5),
  ('Round Cinamon Spice','units',225.0),
  ('Saffron (tube)','tube',89.0),
  ('Sage (kg)','kg',149.0),
  ('Sage (pkt)','pkt',24.75),
  ('Sage (pkt) 100gr','units',22.9),
  ('Salt (KG)','kg',25.95),
  ('Salty-fingers (pkt)','pkt',23.5),
  ('Samble Mix (kg)','kg',65.5),
  ('Samphire (pkt)','pkt',32.5),
  ('Santa Claus-Melon (kg)','kg',30.0),
  ('Shallots (kg)','kg',6.5),
  ('Shoots Flower Sunflower (pkt)','pkt',19.75),
  ('Shoots Micro Basil (pkt)','pkt',46.9),
  ('Shoots Micro Beetroot (pun)','pun',46.9),
  ('Shoots Micro Carrot (pkt)','pkt',46.9),
  ('Shoots Micro Coriander (pkt)','pkt',46.9),
  ('Shoots Micro Mustard (pkt)','pkt',46.9),
  ('Shoots Micro Pea (pkt)','pkt',47.9),
  ('Shoots Micro Radish (pkt)','pkt',46.9),
  ('Shoots Micro Red Amaranth (pkt)','pkt',59.0),
  ('Shoots Micro Rocket (pkt)','pkt',46.9),
  ('Shoots Micro Succulent (pkt)','pkt',35.0),
  ('Snow Peas (kg)','kg',298.0),
  ('Snow Peas (pkt)','pkt',37.5),
  ('Sorrel-Blood (pkt)','pkt',29.0),
  ('Sorrel (kg)','kg',99.0),
  ('Soup Mix (kg)','kg',26.75),
  ('Spanspek-Diced (lt)','lt',89.5),
  ('Spanspek-Parisienne (lt)','lt',89.0),
  ('Spanspek-Peeled (kg)','kg',89.0),
  ('Spanspek-Sliced (Kg)','kg',89.0),
  ('Spanspek (box)','box',449.0),
  ('Spanspek (ea)','ea',29.9),
  ('Spanspek (kg)','kg',32.9),
  ('Spice-Biryani (kg)','kg',255.0),
  ('Spice-Butter Chicken (kg)','kg',219.0),
  ('Spice-Garum Masala (kg)','kg',195.0),
  ('Spice-Kashmiri (kg)','kg',280.0),
  ('Spice-Meringa (kg)','kg',250.0),
  ('Spice-Sumac (kg)','kg',460.0),
  ('Spinach-Baby (kg)','kg',169.0),
  ('Spinach-Baby (pkt)','pkt',23.5),
  ('Spinach-Cleaned (kg)','kg',44.8),
  ('Spinach-Deveined (kg)','kg',42.4),
  ('Spinach-Frozen (kg)','kg',36.95),
  ('Spinach-Sliced (kg)','kg',49.9),
  ('Spinach-Whole (bx)','bx',159.9),
  ('Spinach-Whole (kg)','kg',23.8),
  ('Spinach (bunch)','bunch',16.9),
  ('Split Green Peas (kg)','kg',79.0),
  ('Spring Onion (bunch)','bunch',9.9),
  ('Spring Onion (kg)','kg',99.0),
  ('Sprouts-Alfalfa (pun)','pun',16.5),
  ('Sprouts-Bean (kg)','kg',49.0),
  ('Sprouts-Bean (pkt)','pkt',9.95),
  ('Sprouts-Mixed (kg)','kg',85.0),
  ('Sprouts-Mixed (pun)','pun',14.5),
  ('Sprouts-Onion (pkt)','pkt',28.75),
  ('Starfruit (kg)','kg',84.0),
  ('Starfruit (pun)','pun',32.75),
  ('Stirfry-Special (kg)','kg',89.5),
  ('Stirfry Mix (kg)','kg',39.9),
  ('Strawberries-Frozen (kg)','kg',99.0),
  ('Strawberries (kg)','kg',189.9),
  ('Strawberries (pun)','pun',59.9),
  ('Strawberries /XL pkt','units',49.9),
  ('Strawberry-Kebabs (ea)','ea',7.95),
  ('Succulent-Blooms (pkt)','pkt',26.9),
  ('Sugarcane (bundle)','bundle',122.0),
  ('Sweet Corn-Cut (kg)','kg',89.0),
  ('Sweet Corn-Ribs (kg)','kg',59.9),
  ('Sweet Corn (kg)','kg',39.9),
  ('Sweet Corn (pun)','pun',36.5),
  ('Sweet Melon-Diced (lt)','lt',89.0),
  ('Sweet Melon-Peeled (kg)','kg',89.0),
  ('Sweet Melon-Sliced (Kg)','kg',89.0),
  ('Sweet Potato-Battons (kg)','kg',19.0),
  ('Sweet Potato-Chips Fresh (kg)','kg',25.0),
  ('Sweet Potato-Chips Frozen (kg)','kg',69.9),
  ('Sweet Potato-Cubed (kg)','kg',19.7),
  ('Sweet Potato-Fondant (kg)','kg',39.5),
  ('Sweet Potato-Grated (kg)','kg',16.95),
  ('Sweet Potato-Noddles (kg)','kg',49.5),
  ('Sweet Potato-Orange (kg)','kg',16.9),
  ('Sweet Potato-Parisienne (kg)','kg',23.0),
  ('Sweet Potato-Peeled (kg)','kg',19.7),
  ('Sweet Potato-Wedges (Kg)','kg',24.9),
  ('Sweet Potato-Whole (kg)','kg',14.9),
  ('Sweet Potato - Sliced (kg)','kg',24.5),
  ('Sweet Potato & B.Nut Mix (kg)','kg',9.95),
  ('Sweet Potato (bag)','bag',119.0),
  ('Sweetmelon-Parisienne (lt)','lt',89.0),
  ('Sweetmelon-Sliced (Kg)','kg',89.0),
  ('Sweetmelon (box)','box',298.4),
  ('Sweetmelon (ea)','ea',43.8),
  ('Sweetmelon (kg)','kg',32.9),
  ('Swiss Chard (kg)','kg',65.0),
  ('Tamarillo (pkt)','pkt',19.5),
  ('Tarragon (kg)','kg',145.0),
  ('Tarragon (pkt)','pkt',29.75),
  ('Tatsoi (kg)','kg',75.0),
  ('Thyme (kg)','kg',129.0),
  ('Thyme (pkt)','pkt',27.5),
  ('Thyme (pkt) 100gr','units',19.5),
  ('Tomatillos (pkt)','pkt',28.5),
  ('Tomato-Cocktail (kg)','kg',85.7),
  ('Tomato-Cocktail (pkt)','pkt',22.4),
  ('Tomato-Cocktail XL (pun)','pun',27.5),
  ('Tomato-Diced /kg','units',39.5),
  ('Tomato-Exotic (pun)','pun',28.5),
  ('Tomato-Exotic Mix (Kg)','kg',139.0),
  ('Tomato-Plum (box)','box',135.0),
  ('Tomato-Plum (kg)','kg',24.9),
  ('Tomato-Plum (pkt)','pkt',11.5),
  ('Tomato-Sundried (kg)','kg',359.0),
  ('Tomato-Yellow Cocktail (pkt)','pkt',15.0),
  ('Tomato (box)','box',156.7),
  ('Tomato (kg)','kg',24.9),
  ('Tomato Cocktail Yellow (Kg)','kg',119.0),
  ('Tomato on vine (Kg)','kg',69.0),
  ('Tomato on Vine (pkt)','pkt',37.75),
  ('Turmeric (kg)','kg',79.5),
  ('Turnips-Baby (kg)','kg',89.0),
  ('Turnips-Baby (pkt)','pkt',18.95),
  ('Turnips (kg)','kg',18.9),
  ('Vinegar (kg)','kg',8.0),
  ('Waterblommetjies (kg)','kg',79.5),
  ('Waterblommetjies (pkt)','pkt',39.5),
  ('Watercress (kg)','kg',158.0),
  ('Watercress (pkt)','pkt',22.5),
  ('Watermelon-Diced (lt)','lt',39.0),
  ('Watermelon-Large (ea)','ea',108.0),
  ('Watermelon-Parrisienne (lt)','lt',89.0),
  ('Watermelon-Sliced (Kg)','kg',89.0),
  ('Watermelon-Sugar Baby (kg)','kg',59.7),
  ('Watermelon (box)','box',169.0),
  ('Watermelon (ea)','ea',72.5),
  ('Watermelon (kg)','kg',13.9),
  ('Wheatgrass (tray)','tray',99.0),
  ('Xmas Crackers (ea)','ea',15.0),
  ('Yoghurt-Assorted (kg)','kg',64.5),
  ('Zotato-Gnocchi (kg)','kg',150.0)
) AS v(name, unit, price)
WHERE NOT EXISTS (
  SELECT 1 FROM pp_stock_items s WHERE s.org_id = o.id AND lower(s.name) = lower(v.name)
);
